<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/04 13:00:15

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'karen1',
  'name' => 'doctrine',
)),);
